### ISSUE TITLE
Add browser compatibility section to the FAQ

### ISSUE THREAD

**Issue by jmeas** [6to5/6to5-library-boilerplate#78]
@thejameskyle, I haven't run any integration tests with 6to5. Do you know what support we get from using 6to5 to transpile + polyfill? Is it just IE8, or does it go even lower?

**Comment by thejameskyle** [comment]
http://kangax.github.io/compat-table/es6/ is run against IE8.

**Comment by jmeas** [comment]
Perfect. Thanks!
