### ISSUE TITLE
bundle tests for browser

### ISSUE THREAD

**Issue by thejameskyle** [6to5/6to5-library-boilerplate#91]
Rather than having to update the runner.html file it'd be nice if the unit tests were bundled and automatically included

**Comment by jmeas** [comment]
I wasn't sure about this, cause it seems kind of magical. I do this for my es6 apps, though, and it works great. So maybe I will!

**Comment by thejameskyle** [comment]
It would be nice to be able to use es6 in the tests as well

**Comment by jmeas** [comment]
> It would be nice to be able to use es6 in the tests as well

I thought so, too, until doing that made the tests fail in the Node env.

**Comment by thejameskyle** [comment]
It should work fine, put up a branch?

**Comment by jmeas** [comment]
Will tmrw

**Comment by paulfalgout** [comment]
yes please :+1:

**Comment by jmeas** [comment]
Dang...I did this somewhere and I forget which project it was!
